### ISSUE TITLE
Unable to connect to remote host - Private key decode error

### ISSUE THREAD

**Issue by skra72** [ChaosinaCan/vscode-remote-x11#14]
Hi,

when I'm using the Remote X11 extension in VSC on macOS I get this error when connecting:

> Error: Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR

Looks like the private key in .ssh/id_rsa cannot be read. However, the Remote-SSH extension does using the same setup for public key authentication without problems.

Any idea how to get Remote X11 working, too?

**Comment by ChaosinaCan** [comment]
This error message isn't from anything in my extension. My best guess is it's being returned by the SSH server.

What did you use to generate that key? Googling that error message brings up a couple results that may help:

https://github.com/liximomo/vscode-sftp/issues/594
https://github.com/Eugeny/terminus/issues/666

**Comment by ChaosinaCan** [comment]
Another thing you can try is adding the key to an SSH agent and switching `remoteX11.SSH.authenticationMethod` to `agent`. I don't have a Mac so I don't know what (if anything) you need to set `remoteX11.SSH.agent` to though.

**Comment by skra72** [comment]
Seems to be a strange openssl issue on my dev system. I tested everything on another one and there it works.

Anyway, thanks for your help!
