### ISSUE TITLE
WSL2 support

### ISSUE THREAD

**Issue by Eggiverse** [ChaosinaCan/vscode-remote-x11#18]
In WSL2, linux cannot connect to X server in windows via localhost. 
Details are in
https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-network-applications.
I think it is better if the extension can automatically connect to the correct ip for WSL2.

**Comment by Eggiverse** [comment]
`export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0.0`
works for wsl2

I think it is possible to add Display Command for wsl

**Comment by ChaosinaCan** [comment]
I do plan to support WSL2 as soon as it's available for my PC so I can test it. I'm not running an insider build, so I don't have it yet.

Thanks for the documentation link! It looks like it'll be easy to add.
