### ISSUE TITLE
Nothing happens on Windows host + Ubuntu Vagrant machine

### ISSUE THREAD

**Issue by gretzteam** [ChaosinaCan/vscode-remote-x11#8]
I managed to make this work manually with the following steps:

1. Install VcXsrv on Windows10 host and launch

2. Open cmd.exe on windows:
```
set DISPLAY=localhost:0
ssh -XY -v -p 2222 -i C:\vag0\.vagrant\machines\default\virtualbox\private_key vagrant@127.0.0.1
```
This opens up an ssh connection and bash prompt on vagrant box. I can then try:
```
vagrant@ubuntu-bionic:~$ echo $DISPLAY
localhost:10.0
```
Within this prompt, if I try 'xeyes', it gets displayed properly on VcXsrv.

3. Add the DISPLAY variable to the .bashrc in the vagrant box:
```
export DISPLAY=localhost:10.0
```

4. Launch VSCODE and connect to the vagrant box using ssh. Xeyes works as well as long as the other prompt is opened.

I thought that step 2 would be done automatically (and maybe 3, though I don't mind having it in the bashrc). Nothing really happens and I'm not sure which log to look at.

Thanks!

**Comment by gretzteam** [comment]
Update: this actually works fine. Had to reinstall the vscode server on the ssh client for some reason.
Great extension! 
Thanks

**Comment by ChaosinaCan** [comment]
Huh. No idea what would cause that, but I'm glad it fixed itself after a re-install!
